name: deploy-astro

on:
  push:
    branches: [main]

jobs:
  init_project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: install dependencies
        run: |
          pip install uv
          uv pip install -r requirements.txt