name: deploy-astro

on:
  push:
    branches: [main]

jobs:
  init_project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # - name: python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.12'
      # - name: install dependencies
      #   run: |
      #     pip install uv
      # - name: virtual environment
      #   run: |
      #     uv venv
      #     source .venv/bin/activate
      #     uv pip install -r requirements.txt pytest
      - name: Install Astro CLI
        run: |
          curl -sSL https://install.astronomer.io | sudo bash -s

      - name: Run pytest for dags
        run: |
          astro dev pytest