name: Deploy to Astro

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Test DAGs
      run: |
        pip install -r requirements.txt

      env:
        ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
